feat: create single backcover page content
graasp/epub-gen pull request #12
Opened 2019-07-23 07:50 UTC by pyphilia

closes #11

2019-07-23 16:44 UTC, juancarlosfarah requested changes
Some very minor changes. Also, have you tested that this doesn't affect the single-space exports?

2019-07-23 16:44 UTC, juancarlosfarah commented on templates/epub3/content.opf.ejs
> +        <% if(backCover){ %>
Space after `if`

2019-07-23 16:44 UTC, juancarlosfarah commented on templates/epub3/content.opf.ejs
> +        <% if(backCover){ %>
Space after `if`

2019-07-23 16:44 UTC, juancarlosfarah commented on lib/index.js
> +      if(this.options.backCover) {
Space after `if`

2019-07-23 16:44 UTC, juancarlosfarah commented on lib/index.js
> +      if(this.options.backCover) {
Space after `if`

2019-07-24 07:56 UTC, pyphilia commented
Yes I always test both.

2019-07-24 14:54 UTC, juancarlosfarah approved these changes

2019-07-24 14:54 UTC, merged